from typing import Protocol, TypeVar, Optional, List, Any

T = TypeVar("T")

class IRepository(Protocol[T]):
    async def find_by_id(self, id: int) -> Optional[T]: ...
    async def find_all(self) -> List[T]: ...
    async def create(self, data: Any) -> T: ...
    async def update(self, id: int, data: Any) -> Optional[T]: ...
    async def delete(self, id: int) -> bool: ...
